title: Pages Clone Test
description: | 
  Objective: Create a replica of an existing website that would enable users to perform updates safely before implementing changes on HfLA's live website. I will be using the guidepages prototype for this project.
safe: true


